name: macOS libVLC (debug tools)

on:
  workflow_dispatch:

jobs:
  build-libvlc-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        ARCH: [aarch64]
    env:
      ARGS: -i z -c -g l
    steps:
      - uses: actions/checkout@v4

      - name: Use Java 8 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '8'

      - name: Install build deps (Homebrew)
        run: |
          brew update
          brew install cmake ninja meson pkg-config ant automake autoconf libtool nasm yasm gettext gnu-sed

      - name: Clone VLC
        run: |
          set -euo pipefail
          git clone https://code.videolan.org/videolan/vlc
          cd vlc
          # (Optional) pin to a known-good tag while debugging:
          # git checkout 3.0.21-1
          printf 'BLURAY_CONF += --disable-bdjava-jar\n' > contrib/config.mak

      - name: Build extras/tools (verbose, single job)
        run: |
          set -euxo pipefail
          cd vlc/extras/tools
          ./bootstrap
          # single-threaded to make the failing step obvious
          make V=1 -j1 2>&1 | tee ../../tools_build.log

      - name: Build VLC (macOS)
        env:
          PATH: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        run: |
          set -euxo pipefail
          cd vlc
          mkdir -p build && cd build
          ../extras/package/macosx/build.sh ${ARGS} -a ${{ matrix.ARCH }} \
          || { echo "=== LOGS (searching) ==="; find .. -name "*.log" -maxdepth 6 -print -exec tail -n +1 {} \; ; exit 1; }

          # normalize dylib names
          rm -f macos-install/lib/libvlc.dylib  macos-install/lib/libvlccore.dylib
          cp "$(ls macos-install/lib/libvlc.*.dylib | head -n 1)"      macos-install/lib/libvlc.dylib
          cp "$(ls macos-install/lib/libvlccore.*.dylib | head -n 1)" macos-install/lib/libvlccore.dylib

      - name: Upload libVLC artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libvlc-macos-${{ matrix.ARCH }}
          path: |
            vlc/build/macos-install/include/*
            vlc/build/macos-install/libexec/*
            vlc/build/macos-install/lib/pkgconfig/*
            vlc/build/macos-install/lib/vlc/**/*.dylib
            vlc/build/macos-install/lib/libvlc.dylib
            vlc/build/macos-install/lib/libvlccore.dylib
