name: macOS libVLC (stable, no-tools)

on:
  workflow_dispatch:

jobs:
  build-libvlc-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        ARCH: [aarch64] # Add x86_64 if you need Intel builds too
    env:
      ARGS: -c # Just rebuild contribs and VLC (no invalid flags)
    steps:
      - uses: actions/checkout@v4

      # Use Java 8 so libbluray BD-J compiles cleanly
      - name: Use Java 8 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '8'

      # Install system dependencies so we can skip extras/tools entirely
      - name: Install build deps (Homebrew)
        run: |
          brew update
          brew install cmake ninja meson pkg-config ant automake autoconf libtool nasm yasm gettext gnu-sed

      - name: Clone VLC (pin to stable tag)
        run: |
          set -euxo pipefail
          git clone https://code.videolan.org/videolan/vlc
          cd vlc
          git fetch --tags
          # Pick a stable VLC 3.0.x tag
          git checkout 3.0.21

          # Pretend extras/tools already built so build.sh won't redo them
          mkdir -p extras/tools
          touch extras/tools/.builddone extras/tools/.buildcmake extras/tools/.buildninja extras/tools/.buildmeson

      - name: Build VLC (macOS)
        env:
          PATH: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
          CC: clang
          CXX: clang++
          MAKEFLAGS: -j1 # Avoid jobserver quirks in GitHub Actions
        run: |
          set -euxo pipefail
          cd vlc
          mkdir -p build && cd build
          ../extras/package/macosx/build.sh ${ARGS} -a ${{ matrix.ARCH }} \
          || { echo "=== LOGS ==="; find .. -name "*.log" -maxdepth 6 -print -exec tail -n +1 {} \; ; exit 1; }

          # Normalize dylib names (remove version suffixes)
          rm -f macos-install/lib/libvlc.dylib macos-install/lib/libvlccore.dylib
          cp "$(ls macos-install/lib/libvlc.*.dylib | head -n 1)"      macos-install/lib/libvlc.dylib
          cp "$(ls macos-install/lib/libvlccore.*.dylib | head -n 1)" macos-install/lib/libvlccore.dylib

      - name: Upload libVLC artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libvlc-macos-${{ matrix.ARCH }}
          path: |
            vlc/build/macos-install/include/*
            vlc/build/macos-install/libexec/*
            vlc/build/macos-install/lib/pkgconfig/*
            vlc/build/macos-install/lib/vlc/**/*.dylib
            vlc/build/macos-install/lib/libvlc.dylib
            vlc/build/macos-install/lib/libvlccore.dylib
