name: Build VLC and Unity Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-libvlc-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ANDROID_ABI: [armeabi-v7a]
    container:
      image: registry.videolan.org/vlc-debian-android:20240723100046
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build VLC Android
        run: |
          git clone https://code.videolan.org/videolan/vlc-android && cd vlc-android
          git clone https://code.videolan.org/videolan/libvlcjni && cd libvlcjni
          git clone https://code.videolan.org/videolan/vlc/ --depth=1
          git apply ../../patches/no-libvlcjni-build.patch
          cd ..
          ANDROID_HOME=/sdk/android-sdk-linux ./buildsystem/compile.sh -l -b -r -a ${{ matrix.ANDROID_ABI }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libvlc-android-${{ matrix.ANDROID_ABI }}
          path: vlc-android/**

  build-unity-plugin-android:
    runs-on: ubuntu-latest
    needs: build-libvlc-android
    strategy:
      matrix:
        ANDROID_ABI: [armeabi-v7a]
    container:
      image: registry.videolan.org/vlc-debian-android:20240723100046
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download libVLC artifacts
        uses: actions/download-artifact@v4
        with:
          name: libvlc-android-${{ matrix.ANDROID_ABI }}
          path: vlc-android
      - name: Build Unity Plugin
        run: |
          export PATH="$HOME/sandbox/bin:$PATH"
          PKG_CONFIG_PATH=./vlc-android/libvlcjni/libvlc/jni/pkgconfig/${{ matrix.ANDROID_ABI }} meson setup --cross-file=cross/android-${{ matrix.ANDROID_ABI }}-ndk25.txt build_android_${{ matrix.ANDROID_ABI }} --buildtype release
          ninja -C build_android_${{ matrix.ANDROID_ABI }}
      - name: Upload Unity Plugin Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unity-plugin-android-${{ matrix.ANDROID_ABI }}
          path: |
            build_android_${{ matrix.ANDROID_ABI }}/PluginSource/libVLCUnityPlugin.so
            vlc-android/libvlcjni/libvlc/jni/libs/${{ matrix.ANDROID_ABI }}/libvlc.so
            vlc-android/libvlcjni/libvlc/jni/libs/${{ matrix.ANDROID_ABI }}/libc++_shared.so
